### ISSUE TITLE
Service crashes when there is no internet connection

### ISSUE THREAD

**Issue by mephistopheles1010** [bsgworld/bsg-nodejs#3]
Need to fix error handling in the "remoteCall" method(file: bsg-nodejs/lib/bsg.js). Mismatch error variable name in "request" callback function(file:52). And mismatch error variable name in subsequent try/catch statement(file:58).

Current error callstack:
/path/to/dir/node_modules/bsg-nodejs/lib/bsg.js:52
                                                                reject( `BSG server rejected request on HTTP level: ${e}` );
                                                                                                                      ^

ReferenceError: e is not defined
    at Request._callback (/path/to/dir/node_modules/bsg-nodejs/lib/bsg.js:52:63)
    at self.callback (/path/to/dir/node_modules/bsg-nodejs/node_modules/request/request.js:186:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/path/to/dir/node_modules/bsg-nodejs/node_modules/request/request.js:845:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by Naurzalin** [comment]
Thank you, fixed.
